CineSearch\TdcpBundle\Entity\Cinema:
    type: entity
    table: null
    repositoryClass: CineSearch\TdcpBundle\Entity\CinemaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
        adresse:
            type: text
        lat:
            type: float
        lng:
            type: float

    lifecycleCallbacks: {  }
