CineSearch\TdcpBundle\Entity\Films:
    type: entity
    table: films
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        genre:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        acteurs:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
        cinema:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        date:
            type: datetime
            nullable: false
        synopsis:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
